[build]
builder = "nixpacks"
buildCommand = "npm run build:shared && npm run build:api"

[deploy]
startCommand = "npm run db:migrate -w packages/api -- --skip-generate && npm run db:seed && node packages/api/dist/index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
